name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

- name: rust-toolchain
  # You may pin to the exact commit or the version.
  # uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
  uses: actions-rs/toolchain@v1.0.6
  with:
    # Rust toolchain name.

See https://github.com/rust-lang/rustup.rs#toolchain-specification

If this is not given, the action will try and install the version specified in the `rust-toolchain` file.

    toolchain: # optional
    # Target triple to install for this toolchain
    target: # optional
    # Set installed toolchain as default
    default: # optional
    # Set installed toolchain as an override for a directory
    override: # optional
    # Name of the group of components to be installed for a new toolchain
    profile: # optional
    # Comma-separated list of components to be additionally installed for a new toolchain
    components: # optional
